services:
  backend:
    build:
      context: ./hoit-backend
      dockerfile: Dockerfile
      args:
        MODE: prod
    container_name: hoit-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./hoit-backend/.env
    working_dir: /app
    command: >
      gunicorn --workers 4
               --worker-class uvicorn.workers.UvicornWorker
               --bind 0.0.0.0:8000
               --access-logfile -
               --error-logfile -
               app.main:app
