/**
 * Design System Demo Constants
 * Contains all hardcoded values used throughout the design system demo pages
 */

export const DESIGN_SYSTEM_CONSTANTS = {
  // === SPACING VALUES ===
  MAIN_CONTAINER_PADDING: 8,
  MAIN_CONTENT_VERTICAL_PADDING: 12,
  HEADER_SECTION_MARGIN_BOTTOM: 12,
  SECTION_MARGIN_BOTTOM: 8,
  SUBSECTION_MARGIN_BOTTOM: 6,
  CARD_PADDING: 6,
  DEMO_HEADER_MARGIN: 6,
  DEMO_DESCRIPTION_MARGIN: 8,
  DEMO_SECTIONS_SPACING: 6,
  DEMO_SUBSECTION_SPACING: 4,
  SECTION_TITLE_MARGIN: 4,
  SUBSECTION_HEADER_MARGIN: 2,
  COMPONENT_SECTIONS_SPACING: 12,

  // === COMPONENT SPACING ===
  BUTTON_GROUP_GAP: 3,
  SWITCH_LIST_SPACING: 3,
  SWITCH_COMPONENTS_GAP: 4,
  TAG_COMPONENTS_GAP: 2,

  // === GRID LAYOUT VALUES ===
  GRID_COLS_SMALL: 1,
  GRID_COLS_MEDIUM: 2,
  GRID_COLS_LARGE: 4,
  SURFACE_GRID_COLS: 3,
  MODAL_CONTENT_GRID_COLS: 2,
  GRID_GAP: 4,
  PROGRESS_GRID_GAP: 6,

  // === CONTAINER SIZES ===
  MAIN_CONTENT_MAX_WIDTH: '4xl', // 768px

  // === PROGRESS VALUES ===
  DEMO_PROGRESS_BASIC: 65,
  DEMO_PROGRESS_DOWNLOAD: 45,
  DEMO_PROGRESS_UPLOAD: 80,
  DEMO_PROGRESS_PROCESSING: 25,
  DEMO_PROGRESS_LOADING: 90,
  PROGRESS_SIZE_DEMO_VALUE: 75,
  PROGRESS_VARIANT_DEMO_VALUE: 60,
  PROGRESS_CIRCLE_SMALL: 25,
  PROGRESS_CIRCLE_MEDIUM: 50,
  PROGRESS_CIRCLE_LARGE: 75,
  PROGRESS_CIRCLE_XL: 90,
  PROGRESS_INCREMENT: 10,
  PROGRESS_MIN_VALUE: 0,
  PROGRESS_MAX_VALUE: 100,

  // === MODAL DIMENSIONS (px) ===
  MODAL_SMALL_WIDTH: 384,
  MODAL_MEDIUM_WIDTH: 448,
  MODAL_LARGE_WIDTH: 512,

  // === SLIDER VALUES ===
  DEFAULT_SLIDER_VALUE: 50,
  SLIDER_MIN_VALUE: 0,
  SLIDER_MAX_VALUE: 100,
  CUSTOM_SLIDER_MIN: 20,
  CUSTOM_SLIDER_MAX: 80,
  CUSTOM_SLIDER_VALUE: 50,

  // === DEMO CONTENT ===
  SCROLLABLE_CONTENT_ITEMS: 15,
  SECTION_INDEX_OFFSET: 1,
  INPUT_PADDING: 2,

  // === TAILWIND CLASS SHORTCUTS ===
  SPACING_CLASSES: {
    MAIN_CONTAINER: 'p-8',
    MAIN_CONTENT: 'py-12',
    HEADER_SECTION: 'mb-12',
    SECTION: 'mb-8',
    SUBSECTION: 'mb-6',
    CARD: 'p-6',
    DEMO_SECTIONS: 'space-y-6',
    DEMO_SUBSECTIONS: 'space-y-4',
    SWITCH_LIST: 'space-y-3',
    TAG_COMPONENTS: 'gap-2',
    BUTTON_GROUP: 'gap-3',
    GRID_GAP: 'gap-4',
    PROGRESS_GRID_GAP: 'gap-6',
  },

  GRID_CLASSES: {
    SMALL: 'grid-cols-1',
    MEDIUM: 'md:grid-cols-2',
    LARGE: 'md:grid-cols-4',
    SURFACE: 'md:grid-cols-3',
  },

  CONTAINER_CLASSES: {
    MAIN_CONTENT: 'max-w-4xl',
  },
} as const

// Type for accessing constants
export type DesignSystemConstants = typeof DESIGN_SYSTEM_CONSTANTS

// Helper functions for common patterns
export const getSpacingClass = (
  type: keyof typeof DESIGN_SYSTEM_CONSTANTS.SPACING_CLASSES
) => {
  return DESIGN_SYSTEM_CONSTANTS.SPACING_CLASSES[type]
}

export const getGridClass = (
  type: keyof typeof DESIGN_SYSTEM_CONSTANTS.GRID_CLASSES
) => {
  return DESIGN_SYSTEM_CONSTANTS.GRID_CLASSES[type]
}

export const getProgressValue = (
  type: 'basic' | 'download' | 'upload' | 'processing' | 'loading'
) => {
  const valueMap = {
    basic: DESIGN_SYSTEM_CONSTANTS.DEMO_PROGRESS_BASIC,
    download: DESIGN_SYSTEM_CONSTANTS.DEMO_PROGRESS_DOWNLOAD,
    upload: DESIGN_SYSTEM_CONSTANTS.DEMO_PROGRESS_UPLOAD,
    processing: DESIGN_SYSTEM_CONSTANTS.DEMO_PROGRESS_PROCESSING,
    loading: DESIGN_SYSTEM_CONSTANTS.DEMO_PROGRESS_LOADING,
  }
  return valueMap[type]
}
