name: Deploy Frontend to S3 (Monorepo)

on:
  push:
    branches:
      - main
    paths:
      - "hoit-frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: hoit-frontend
        run: npm ci

      - name: Build Frontend
        working-directory: hoit-frontend
        run: npm run build

      - name: Deploy to S3
        uses: aws-actions/s3-sync@v4
        with:
          source: hoit-frontend/out
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          region: ${{ secrets.AWS_REGION }}
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deployment Complete
        run: echo "✅ Frontend deployed successfully to S3!"
