name: Deploy Frontend to S3 (Yarn Monorepo)

on:
  push:
    branches:
      - main
    paths:
      - "hoit-frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Install Dependencies
        working-directory: hoit-frontend
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Create .env.production for Build
        working-directory: hoit-frontend
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env.production
          echo "NEXT_PUBLIC_MOTIONTEXT_PLUGIN_ORIGIN=${{ secrets.NEXT_PUBLIC_MOTIONTEXT_PLUGIN_ORIGIN }}" >> .env.production
          echo "NODE_ENV=production" >> .env.production
        shell: bash

      - name: Build Frontend
        working-directory: hoit-frontend
        run: yarn build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: hoit-frontend/out

      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deployment Complete
        run: echo "✅ Frontend deployed successfully to S3 and CloudFront!"
